const assert=require('assert/strict'),fs=require('fs'),path=require('path');
const {JSDOM,VirtualConsole}=require(process.env.EMMY_JSDOM_MODULE||'jsdom');
(async()=>{
 const root=path.resolve(__dirname,'../src/Emmy.Host/wwwroot'),token=fs.readFileSync(process.env.EMMY_TEST_TOKEN_FILE,'utf8').trim();
 const errors=[],virtualConsole=new VirtualConsole();virtualConsole.on('jsdomError',e=>errors.push(e.message));
 const api=async(route,method='GET',body)=>{const response=await fetch('http://127.0.0.1:17840/api/'+route,{method,headers:{'X-Emmy-Token':token,'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});const text=await response.text();assert.equal(response.status,200,text);return text?JSON.parse(text):null;};
 const world={clientId:'dom-visit',zoneGeneration:1,self:{name:'Emmy Miranda',homeWorld:21,worldName:'Ragnarok'},territory:100,currentWorld:21,position:{x:0,y:0,z:0},entities:[{id:99,identity:{name:'Entrance',homeWorld:0},position:{x:1,y:0,z:0},targetable:true,kind:'EventObj'}],menu:null,canAct:true,navReady:true,navBusy:false,travelReady:true,travelBusy:false,locationKey:'housing-outdoor:3:1'};
 const bridge=()=>api('bridge','POST',{protocol:1,world:{...world,at:new Date().toISOString()},messages:[],results:[],frame:null});
 let settings=(await api('state')).settings;await api('settings','PUT',{...settings,movement:true,menus:true,vision:true});
 await bridge();await api('place','POST',{text:'DOM entrance'});
 world.zoneGeneration=2;world.territory=101;world.locationKey='housing-indoor:1234:0';await bridge();await api('place','POST',{text:'DOM room'});
 world.zoneGeneration=3;world.territory=100;world.locationKey='housing-outdoor:3:1';await bridge();
 const dom=new JSDOM(fs.readFileSync(root+'/index.html','utf8'),{url:'http://127.0.0.1:17840/#'+token,runScripts:'outside-only',pretendToBeVisual:true,virtualConsole});
 dom.window.fetch=(url,options)=>fetch(new URL(url,'http://127.0.0.1:17840'),options);
 dom.window.eval(fs.readFileSync(root+'/app.js','utf8'));
 const document=dom.window.document,wait=()=>new Promise(r=>setTimeout(r,100));await wait();
 assert.match(document.getElementById('connection').textContent,/Spielclient/);
 assert.equal(document.getElementById('cards').children.length,3);
 document.querySelector('[data-page="persona"]').click();assert.equal(document.getElementById('persona').hidden,false);
 document.querySelector('[data-page="memory"]').click();assert.equal(document.getElementById('memory').hidden,false);assert.equal(document.getElementById('persona').hidden,true);
 const style=fs.readFileSync(root+'/style.css','utf8');assert.ok(style.includes('@media(max-width:550px)'));
 const key=document.getElementById('key-status').textContent;assert.ok(key.includes('API-Schlüssel'));
 document.getElementById('test').click();await wait();assert.match(document.getElementById('test-result').textContent,/Kein API/);
 document.querySelector('[data-page="abilities"]').click();
 const places=(await api('state')).places;
 document.getElementById('visit-entrance').value=places.find(p=>p.name==='DOM entrance').id;
 document.getElementById('visit-room').value=places.find(p=>p.name==='DOM room').id;
 document.getElementById('visit-prompt').value='Das Haus betreten?';document.getElementById('visit-option').value='Ja';
 document.getElementById('visit-form').dispatchEvent(new dom.window.Event('submit',{bubbles:true,cancelable:true}));await wait();
 assert.equal((await api('state')).itinerary.steps.length,5);assert.equal((await api('state')).visit.status,'Unterwegs');
 document.getElementById('stop').click();await wait();assert.deepEqual(errors,[]);
 assert.notEqual((await api('state')).visit.status,'Unterwegs');
 dom.window.close();console.log('DOM checks passed: render, navigation, settings fields, provider failure, configured house-visit submission and stop controls. Visual layout remains unverified here.');
})().catch(e=>{console.error(e);process.exit(1)});
