const assert=require('assert/strict'),fs=require('fs'),path=require('path');
const {JSDOM,VirtualConsole}=require(process.env.EMMY_JSDOM_MODULE||'jsdom');
(async()=>{
 const root=path.resolve(__dirname,'../src/Emmy.Host/wwwroot'),token=fs.readFileSync(process.env.EMMY_TEST_TOKEN_FILE,'utf8').trim();
 const errors=[],virtualConsole=new VirtualConsole();virtualConsole.on('jsdomError',e=>errors.push(e.message));
 const api=async(route,method='GET',body)=>{const response=await fetch('http://127.0.0.1:17840/api/'+route,{method,headers:{'X-Emmy-Token':token,'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});const text=await response.text();assert.equal(response.status,200,text);return text?JSON.parse(text):null;};
 const world={clientId:'dom-visit',zoneGeneration:1,self:{name:'Emmy Miranda',homeWorld:21,worldName:'Ragnarok'},territory:100,currentWorld:21,position:{x:0,y:0,z:0},entities:[{id:99,identity:{name:'Entrance',homeWorld:0},position:{x:1,y:0,z:0},targetable:true,kind:'EventObj'}],menu:null,canAct:true,navReady:true,navBusy:false,travelReady:true,travelBusy:false,locationKey:'housing-outdoor:3:1'};
 const bridge=(results=[])=>api('bridge','POST',{protocol:1,world:{...world,at:new Date().toISOString()},messages:[],results,frame:null});
 let settings=(await api('state')).settings;await api('settings','PUT',{...settings,movement:true,menus:true,vision:true});
 await bridge();await api('place','POST',{text:'DOM entrance'});
 world.zoneGeneration=2;world.territory=101;world.locationKey='housing-indoor:1234:0';await bridge();await api('place','POST',{text:'DOM room'});
 world.zoneGeneration=3;world.territory=100;world.locationKey='housing-outdoor:3:1';await bridge();
 const dom=new JSDOM(fs.readFileSync(root+'/index.html','utf8'),{url:'http://127.0.0.1:17840/#'+token,runScripts:'outside-only',pretendToBeVisual:true,virtualConsole});
 dom.window.fetch=(url,options)=>fetch(new URL(url,'http://127.0.0.1:17840'),options);
 dom.window.eval(fs.readFileSync(root+'/app.js','utf8'));
 const document=dom.window.document,wait=()=>new Promise(r=>setTimeout(r,100));await wait();
 assert.match(document.getElementById('connection').textContent,/Spielclient/);
 assert.equal(document.getElementById('cards').children.length,3);
 document.querySelector('[data-page="persona"]').click();assert.equal(document.getElementById('persona').hidden,false);
 document.querySelector('[data-page="memory"]').click();assert.equal(document.getElementById('memory').hidden,false);assert.equal(document.getElementById('persona').hidden,true);
 const style=fs.readFileSync(root+'/style.css','utf8');assert.ok(style.includes('@media(max-width:550px)'));
 const key=document.getElementById('key-status').textContent;assert.ok(key.includes('API-Schlüssel'));
 document.getElementById('test').click();await wait();assert.match(document.getElementById('test-result').textContent,/Kein API/);
 document.querySelector('[data-page="abilities"]').click();
 const places=(await api('state')).places;
 document.getElementById('visit-entrance').value=places.find(p=>p.name==='DOM entrance').id;
 document.getElementById('visit-room').value=places.find(p=>p.name==='DOM room').id;
 document.getElementById('visit-prompt').value='Das Haus betreten?';document.getElementById('visit-option').value='Ja';
 document.getElementById('visit-form').dispatchEvent(new dom.window.Event('submit',{bubbles:true,cancelable:true}));await wait();
 assert.equal((await api('state')).itinerary.steps.length,5);assert.equal((await api('state')).visit.status,'Unterwegs');
 document.getElementById('stop').click();await wait();assert.deepEqual(errors,[]);
 assert.notEqual((await api('state')).visit.status,'Unterwegs');
 await bridge();
 document.querySelector('[data-page="tasks"]').click();assert.equal(document.getElementById('tasks').hidden,false);
 const submitStep=()=>document.getElementById('step-form').dispatchEvent(new dom.window.Event('submit',{bubbles:true,cancelable:true}));
 document.getElementById('step-place').value=places.find(p=>p.name==='DOM entrance').id;submitStep();
 document.getElementById('step-kind').value='Capture';document.getElementById('step-kind').dispatchEvent(new dom.window.Event('change'));submitStep();
 assert.equal(document.getElementById('plan-steps').children.length,2);
 const stepButton=(index,label)=>[...document.getElementById('plan-steps').children[index].querySelectorAll('button')].find(b=>b.textContent===label);
 stepButton(1,'Nach oben').click();await wait();assert.match(document.getElementById('plan-steps').children[0].textContent,/Frisches Bild/);
 stepButton(0,'Nach unten').click();await wait();
 stepButton(1,'Bearbeiten').click();await wait();assert.equal(document.getElementById('step-add').textContent,'Änderung übernehmen');submitStep();
 document.getElementById('plan-title').value='DOM two-step visit';
 await bridge();document.getElementById('plan-start').click();document.getElementById('plan-start').click();await wait();
 let plan=(await api('state')).itinerary;assert.equal(plan.title,'DOM two-step visit');assert.equal(plan.steps.length,2);assert.equal(plan.steps[0].expectedTerritory,100);assert.equal(plan.steps[0].expectedWorld,21);
 assert.equal(document.getElementById('plan-start').disabled,true);
 let dispatch=(await bridge()).actions;assert.equal(dispatch.length,1);assert.equal(dispatch[0].kind,'Move');assert.equal((await bridge()).actions.length,0);
 dispatch=(await bridge([{id:dispatch[0].id,outcome:'Succeeded',detail:'Reached',at:new Date().toISOString()}])).actions;
 assert.equal(dispatch.length,1);assert.equal(dispatch[0].kind,'Capture');
 await bridge([{id:dispatch[0].id,outcome:'Succeeded',detail:'Captured',at:new Date().toISOString()}]);
 await new Promise(r=>setTimeout(r,2700));assert.match(document.getElementById('plan-status').textContent,/Abgeschlossen/);assert.equal(document.getElementById('plan-start').disabled,false);
 document.getElementById('plan-clear').click();assert.equal(document.getElementById('plan-steps').children.length,0);assert.equal(document.getElementById('plan-start').disabled,true);
 assert.deepEqual(errors,[]);
 dom.window.close();console.log('DOM checks passed: render, navigation, settings fields, provider failure, configured house-visit submission, stop, ordered plan editing, double-click protection and confirmed-result progression. Visual layout remains unverified here.');
})().catch(e=>{console.error(e);process.exit(1)});
